import { showUi } from "@stadtteilliebe/react-cookie-consent"
import Head from "next/head"

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main style={{ display: "flex", flexWrap: "wrap", justifyContent: "center" }}>
                <div
                    style={{
                        width: "calc(50% - 50px)",
                        height: "500px",
                        background: "#cfbb0c",
                        margin: "25px",
                        boxSizing: "border-box",
                    }}
                ></div>
                <div
                    style={{
                        width: "calc(50% - 50px)",
                        height: "500px",
                        background: "#6416ac",
                        margin: "25px",
                        boxSizing: "border-box",
                    }}
                ></div>
                <div
                    style={{
                        width: "calc(50% - 50px)",
                        height: "500px",
                        background: "#ac1682",
                        margin: "25px",
                        boxSizing: "border-box",
                    }}
                ></div>
                <div
                    style={{
                        width: "calc(50% - 50px)",
                        height: "500px",
                        background: "#eb9730",
                        margin: "25px",
                        boxSizing: "border-box",
                    }}
                ></div>
            </main>

            <footer>
                <button onClick={showUi}>Cookie-Einstellungen</button>
            </footer>
        </div>
    )
}
