import { Banner } from "@stadtteilliebe/react-cookie-consent"
import Head from "next/head"
import Image from "next/image"

export default function Home() {
    const services = [
        {
            id: "ga",
            title: "Google Analytics",
            description: "Das macht was mit dir",
            category: "Marketing",
        },
        {
            id: "fb",
            title: "Facebook",
            description: "Das macht auch was mit dir",
            category: "Marketing",
        },
        {
            id: "linkedin",
            title: "LinkedIn",
            description: "Das macht was mit dir",
            category: "Marketing",
        },
        {
            id: "prismic",
            title: "Prismic",
            description: "Das macht was mit dir",
            category: "Essentiel",
        },
    ]
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Banner
                    // @ts-ignore - don't know why this happens
                    title="Cookie Consent"
                    content="Uns ist Datenschutz wichtig"
                    services={services}
                />
            </main>

            <footer>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}
